### ISSUE TITLE
There is one error！

### ISSUE THREAD

**Issue by CnaZhao** [free5gc/upf#1]
<img width="499" alt="free5gc_upf" src="https://user-images.githubusercontent.com/48743734/83091772-8ac38d00-a0ce-11ea-8599-bdf8e1be33a3.png">

**Comment by free5gc-org** [comment]
Oh yes,
This is a bug, we'll fix it.
Thanks for your report

**Comment by free5gc-org** [comment]
@CnaZhao 

This issue was already fixed in tag v1.0.0.
Thanks for your report.
