### ISSUE TITLE
CPU load 100%+ for free5gc-upf (free5gc 3.0.4)

### ISSUE THREAD

**Issue by Thorntonchen** [free5gc/upf#11]
you once mentioned : "We’ll change the message queue to blocking in the next stage" in forum.
however,it's still in O_NONBLOCK. (upf_init.c)
static Status EventQueueInit(void *data) {
    Self()->eventQ = EventQueueCreate(O_RDWR | O_NONBLOCK);
if change the value to O_RDWR | 0,the cpu load will be decrease to a reasonable value like 7%.
but,upf was  terminated without any notification to logger in this status.

**Comment by free5gc-org** [comment]
@Thorntonchen 

This issue was already fixed in tag v1.0.0.
Thanks for your report.
