### ISSUE TITLE
globalXactId maintenance error

### ISSUE THREAD

**Issue by Dorian1982** [free5gc/upf#2]
In the PfcpXactLocalCreate function, below line:
xact->transactionId = (globalXactId == PFCP_MAX_XACT_ID ? PFCP_MIN_XACT_ID : globalXactId + 1);

should be:
xact->transactionId = (globalXactId  = (globalXactId == PFCP_MAX_XACT_ID ? PFCP_MIN_XACT_ID : globalXactId + 1));

otherwise, globalXactId will NOT +1

**Comment by free5gc-org** [comment]
This issue was already fixed. Please pull the latest commit (3e10a73c6f64fd7e6378e4248e0703ecc1da9e18).
