### ISSUE TITLE
Test UPF in respect to adding/removing PDRs

### ISSUE THREAD

**Issue by aviweit** [free5gc/upf#27]
I would like to ask whether there is a way to test UPF only, without the involvement of other 5G Core components (e.g. amf, smf, nssf, ..).

I have a kubernetes cluster hosted on ubuntu 20.04 worker nodes installed with gtp5g kernel module. I would like to call into `UpfN4HandleSessionEstablishmentRequest` from a test suite, without the need to install and configure the rest of the 5G core components and then to observe that one end of the tunnel, on the UPF side, get properly created.

Thanks.

**Comment by calee0219** [comment]
You may send your own PFCP message by writing some small program. Maybe you can import [go-pfcp](https://github.com/wmnsk/go-pfcp) module to help to do it.

Remember to send `Association Setup Request` before sending `Establishment Request`.

**Comment by aviweit** [comment]
Hi @calee0219 ,
Thanks. I am using go-pfcp IE's to build Association Setup and Session Establishment requests. If I have more questions or encounter issues, I will ask.
Thanks again.
