### ISSUE TITLE
session->smfSeid error

### ISSUE THREAD

**Issue by Dorian1982** [free5gc/upf#4]
In the UpfSessionAddByMessage function, below line is wrong:
session->smfSeid = *(uint64_t*)request->cPFSEID.value;

It should be like this:
PfcpFSeid *fSeid = (PfcpFSeid *)request->cPFSEID.value;
session->smfSeid = htobe64(fSeid->seid);

**Comment by free5gc-org** [comment]
@Dorian1982 

This issue was already fixed in tag v1.0.0.
Thanks for your report.
