### ISSUE TITLE
len bug in _TlvBuildMessage()

### ISSUE THREAD

**Issue by Dorian1982** [free5gc/upf#7]
In the _TlvBuildMessage function of pfcp_message.c, about line 437:

*lenPtr = htons(bufOffset);

should be:

*(((uint16_t *)(*bufBlkPtr)->buf)+1) = htons(bufOffset);

Otherwise, in case of len is more than 64 (BufblkBuf will be increaded to 128), the lenPtr will be zero. I reproduced this issue by simulating a larger message.

**Comment by free5gc-org** [comment]
@Dorian1982 

This issue was already fixed in tag v1.0.0.
Thanks for your report.
